version: "3.8"
services:
  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    env_file:
      - db.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          memory: 512M

  backend:
    build: .
    restart: unless-stopped
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"

  nginx:
    image: nginx:1.24-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.nginx/https.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.nginx/ssl-dhparam.pem:/etc/nginx/ssl-dhparam.pem:ro
      - certs:/etc/nginx/ssl:ro
      - certbot-www:/var/www/certbot:ro
      - admin_media-files:/home/app/media
      - admin_static-files:/home/app/static
    deploy:
      resources:
        limits:
          memory: 256M

  certbot:
    image: certbot/certbot:v2.6.0
    volumes:
      - certs:/etc/letsencrypt
      - certbot-www:/var/lib/letsencrypt
    command: renew
    deploy:
      resources:
        limits:
          memory: 256M

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    deploy:
      resources:
        limits:
          memory: 512M
  huey:
    build: .
    container_name: huey_worker
    env_file:
      - .env
    depends_on:
      - redis
      - backend
    entrypoint: huey_consumer.py main.huey_config.huey

volumes:
  postgres-data:
  redis-data:
  admin_media-files:
    external: true
  bot-static-files:
  admin_static-files:
    external: true
  certs:
  certbot-www:
#networks:
#  tg-ksenya-chat-bot:
