version: "3.8"
services:
  db:
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    env_file:
      - db.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
#    networks:
#      - tg-ksenya-chat-bot
    deploy:
      resources:
        limits:
          memory: 512M

  backend:
    build: .
    restart: unless-stopped
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - media-files:/var/www/media:ro
      - bot-static-files:/home/app/static
#    deploy:
#      resources:
#        limits:
#          memory: 2G

  nginx:
    image: nginx:1.24-alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./.nginx/https.conf:/etc/nginx/conf.d/default.conf:ro
      - ./.nginx/ssl-dhparam.pem:/etc/nginx/ssl-dhparam.pem:ro
      - certs:/etc/nginx/ssl:ro
      - certbot-www:/var/www/certbot:ro
      - media-files:/var/www/media:ro
      - static-files:/var/www/static:ro
      - bot-static-files:/home/app/static:ro
    deploy:
      resources:
        limits:
          memory: 256M
#
  certbot:
    image: certbot/certbot:v2.6.0
    volumes:
      - certs:/etc/letsencrypt
      - certbot-www:/var/lib/letsencrypt
    command: renew
    deploy:
      resources:
        limits:
          memory: 256M

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis-data:/data
    deploy:
      resources:
        limits:
          memory: 512M

  celery:
    build: .
    restart: unless-stopped
    entrypoint: celery -A main worker -l info
    env_file:
      - .env
    depends_on:
      - redis
      - db
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  celery-beat:
    build: .
    restart: unless-stopped
    entrypoint: celery -A main beat -l info
    env_file:
      - .env
    depends_on:
      - redis
      - db
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

volumes:
  postgres-data:
  redis-data:
  media-files:
  bot-static-files:
  static-files:
  certs:
  certbot-www:
networks:
  tg-ksenya-chat-bot:
