#!/bin/bash
set -e
echo 'steady'
echo "BOT_DB_USER=${BOT_DB_USER}, BOT_DB_NAME=${BOT_DB_NAME}, ${BOT_DB_PASSWORD}"
echo "ADMIN_DB_USER=${ADMIN_DB_USER}, ADMIN_DB_NAME=${ADMIN_DB_NAME}, ${ADMIN_DB_PASSWORD}"

psql -U ${POSTGRES_USER} -v ON_ERROR_STOP=1 <<-EOSQL
	CREATE USER ${BOT_DB_USER} WITH ENCRYPTED PASSWORD '${BOT_DB_PASSWORD}';
	CREATE DATABASE ${BOT_DB_NAME} WITH OWNER ${BOT_DB_USER};
	GRANT ALL PRIVILEGES ON DATABASE ${BOT_DB_NAME} TO ${BOT_DB_USER};

	CREATE USER ${ADMIN_DB_USER} WITH ENCRYPTED PASSWORD '${ADMIN_DB_PASSWORD}';
	CREATE DATABASE ${ADMIN_DB_NAME} WITH OWNER ${ADMIN_DB_USER};
	GRANT ALL PRIVILEGES ON DATABASE ${ADMIN_DB_NAME} TO ${ADMIN_DB_USER};
EOSQL
echo 'ready'